{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fider.serviceAccountName" . }}
  labels:
{{ include "fider.labels" . | indent 4 }}
{{- end -}}
